"use client";

import { BellRing, CheckCircle2, Loader2, Radio, RefreshCw, Search, Send, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { createPushChannel, deletePushChannel, getPushAudit, getPushChannels, testPushChannel, testPushChannelStream, updatePushChannel } from "@/lib/push-api";
import type { PushAudit, PushChannel, PushChannelInput } from "@/lib/push-types";
import { getCodeProjects } from "@/lib/code-repository-api";
import type { CodeProject } from "@/lib/code-repository-types";
import { getAuthStatus } from "@/lib/auth-api";
import { SettingsPageHeader } from "@/components/settings/layout/SettingsShell";

type ChannelDraft = {
  name: string; webhookUrl: string; signSecret: string; clearSignSecret: boolean; enabled: boolean;
  robotCode: string; streamClientId: string; streamClientSecret: string; clearStreamClientSecret: boolean; streamEnabled: boolean; projectIds: number[];
};
const emptyDraft = (): ChannelDraft => ({ name: "", webhookUrl: "", signSecret: "", clearSignSecret: false, enabled: true, robotCode: "", streamClientId: "", streamClientSecret: "", clearStreamClientSecret: false, streamEnabled: false, projectIds: [] });
const fieldClass = "h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none placeholder:text-slate-400 focus:border-blue-400 focus:ring-2 focus:ring-blue-50";
const primaryClass = "inline-flex h-10 items-center justify-center gap-1.5 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50";
const actionClass = "inline-flex h-9 items-center justify-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 text-xs font-medium text-slate-600 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50";

export function PushSettingsPage() {
  const [allowed, setAllowed] = useState<boolean | null>(null);
  const [channels, setChannels] = useState<PushChannel[]>([]);
  const [projects, setProjects] = useState<CodeProject[]>([]);
  const [audit, setAudit] = useState<PushAudit[]>([]);
  const [draft, setDraft] = useState<ChannelDraft>(emptyDraft);
  const [editing, setEditing] = useState<PushChannel | null>(null);
  const [projectSelectorOpen, setProjectSelectorOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");

  const load = async () => { setBusy(true); try { const [nextChannels, nextProjects, nextAudit] = await Promise.all([getPushChannels(), getCodeProjects(), getPushAudit()]); setChannels(nextChannels); setProjects(nextProjects); setAudit(nextAudit); } catch (error) { setMessage(error instanceof Error ? error.message : "读取推送配置失败。"); } finally { setBusy(false); } };
  useEffect(() => { void getAuthStatus().then((status) => setAllowed(status.is_admin === true)).catch(() => setAllowed(false)); }, []);
  useEffect(() => { if (allowed) void load(); }, [allowed]);
  const resetEditor = () => { setEditing(null); setDraft(emptyDraft()); setProjectSelectorOpen(false); };
  const editChannel = (channel: PushChannel) => { setEditing(channel); setProjectSelectorOpen(true); setDraft({ name: channel.name, webhookUrl: "", signSecret: "", clearSignSecret: false, enabled: channel.enabled, robotCode: channel.robot_code || "", streamClientId: channel.stream_client_id || "", streamClientSecret: "", clearStreamClientSecret: false, streamEnabled: channel.stream_enabled, projectIds: channel.project_ids || [] }); };
  const saveChannel = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(""); try { const payload: PushChannelInput = { name: draft.name, webhook_url: draft.webhookUrl || undefined, sign_secret: draft.signSecret || undefined, clear_sign_secret: draft.clearSignSecret, robot_code: draft.robotCode || undefined, stream_client_id: draft.streamClientId || undefined, stream_client_secret: draft.streamClientSecret || undefined, clear_stream_client_secret: draft.clearStreamClientSecret, stream_enabled: draft.streamEnabled, project_ids: draft.projectIds, enabled: draft.enabled }; if (editing) await updatePushChannel(editing.id, payload); else await createPushChannel(payload); resetEditor(); setMessage("推送通道与项目范围已保存；所有 token 和 secret 均不会回显。"); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "保存推送通道失败。"); } finally { setBusy(false); } };
  const sendTest = async (channel: PushChannel) => { if (!window.confirm(`确认向“${channel.name}”对应钉钉群发送固定测试消息？`)) return; setBusy(true); try { setMessage((await testPushChannel(channel.id)).summary); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "测试消息发送失败。"); } finally { setBusy(false); } };
  const testStream = async (channel: PushChannel) => { if (!window.confirm(`确认测试“${channel.name}”的钉钉 Stream 凭据和 WebSocket 连接？不会向群内发送消息。`)) return; setBusy(true); try { setMessage((await testPushChannelStream(channel.id)).summary); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Stream 测试失败。"); } finally { setBusy(false); } };
  const removeChannel = async (channel: PushChannel) => { if (!window.confirm(`确认删除“${channel.name}”？项目通知和 Stream 群机器人也将停止。`)) return; setBusy(true); try { await deletePushChannel(channel.id); if (editing?.id === channel.id) resetEditor(); setMessage("推送通道已删除并停止接收群机器人消息。"); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "删除推送通道失败。"); } finally { setBusy(false); } };

  if (allowed === null) return <Loading />;
  if (!allowed) return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-8 text-center text-sm text-amber-800">推送模块仅对管理员开放。</section>;
  return <section><SettingsPageHeader title="推送模块" description="先配置推送通道，再在通道编辑中勾选可通知、可供群机器人分析的项目。Stream 模式由服务器主动连接钉钉，不需要公网回调地址。" action={null} />
    {message && <p className="mb-5 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-700">{message}</p>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_430px]"><section className="space-y-5"><Panel title="推送通道" detail="通道优先：每个通道可多选项目。勾选的项目才会收到 Git 推送通知，也才允许对应群机器人读取和分析。"><div className="divide-y divide-slate-100">{channels.length === 0 ? <Empty text="尚未配置推送通道" /> : channels.map((channel) => <ChannelRow key={channel.id} channel={channel} busy={busy} onEdit={editChannel} onTest={sendTest} onTestStream={testStream} onDelete={removeChannel} />)}</div></Panel>
      <Panel title="最近审计" detail="仅保留脱敏事件、发送状态与错误码；不会记录 Webhook token 或应用密钥。"><div className="divide-y divide-slate-100">{audit.length === 0 ? <Empty text="暂无推送审计记录" /> : audit.slice(0, 10).map((item) => <div key={item.id} className="grid grid-cols-[1fr_auto_auto] gap-4 px-5 py-3 text-xs"><span className="text-slate-700">{item.action}</span><span className={item.outcome === "success" ? "text-emerald-600" : "text-amber-600"}>{item.outcome}</span><span className="text-slate-400">{item.occurred_at ? new Date(item.occurred_at).toLocaleString() : ""}</span></div>)}</div></Panel>
    </section><aside><form onSubmit={saveChannel} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><BellRing size={18} className="text-blue-600" /><div><h2 className="text-[15px] font-semibold">{editing ? "编辑推送通道" : "新建推送通道"}</h2><p className="mt-1 text-xs text-slate-500">Webhook 用于出站推送；Stream 用于机器人接收群内 @ 消息。</p></div></div>
      <div className="mt-5 space-y-4"><Label text="通道名称"><input required value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} className={fieldClass} placeholder="例如：商城研发群机器人" /></Label><Label text={editing ? "新的钉钉 Webhook（留空则保留）" : "钉钉 Webhook"}><input required={!editing} type="password" value={draft.webhookUrl} onChange={(event) => setDraft((current) => ({ ...current, webhookUrl: event.target.value }))} className={fieldClass} placeholder="https://oapi.dingtalk.com/robot/send?access_token=..." autoComplete="off" /></Label><Label text={editing ? "新的加签 secret（留空则保留）" : "加签 secret（可选）"}><input type="password" value={draft.signSecret} onChange={(event) => setDraft((current) => ({ ...current, signSecret: event.target.value }))} className={fieldClass} placeholder="机器人启用加签时填写" autoComplete="new-password" /></Label>{editing && <Check text="清除已保存的 Webhook 加签 secret" checked={draft.clearSignSecret} onChange={(checked) => setDraft((current) => ({ ...current, clearSignSecret: checked }))} />}<Check text="启用 Git 推送通知通道" checked={draft.enabled} onChange={(checked) => setDraft((current) => ({ ...current, enabled: checked }))} />
        <div className="border-t border-slate-100 pt-4"><div className="flex items-center gap-2"><Radio size={15} className="text-violet-600" /><strong className="text-sm text-slate-800">Stream 事件订阅 / 群机器人</strong></div><p className="mt-1 text-xs leading-5 text-slate-500">在钉钉开发者后台启用机器人 Stream 模式后填写。服务器主动建立长连接，无需公网 IP 或 HTTP 回调。</p><div className="mt-3 grid gap-3"><Label text="机器人 robotCode"><input value={draft.robotCode} onChange={(event) => setDraft((current) => ({ ...current, robotCode: event.target.value }))} className={fieldClass} placeholder="钉钉机器人 robotCode" /></Label><Label text="Stream Client ID（AppKey）"><input value={draft.streamClientId} onChange={(event) => setDraft((current) => ({ ...current, streamClientId: event.target.value }))} className={fieldClass} placeholder="Client ID / AppKey" autoComplete="off" /></Label><Label text={editing ? "新的 Stream Client Secret（留空则保留）" : "Stream Client Secret（AppSecret）"}><input type="password" value={draft.streamClientSecret} onChange={(event) => setDraft((current) => ({ ...current, streamClientSecret: event.target.value }))} className={fieldClass} placeholder="Client Secret / AppSecret" autoComplete="new-password" /></Label>{editing && <Check text="清除已保存的 Stream Client Secret" checked={draft.clearStreamClientSecret} onChange={(checked) => setDraft((current) => ({ ...current, clearStreamClientSecret: checked }))} />}<Check text="启用 Stream 接收 @机器人的文本消息" checked={draft.streamEnabled} onChange={(checked) => setDraft((current) => ({ ...current, streamEnabled: checked }))} /></div></div>
        <div className="border-t border-slate-100 pt-4"><div className="flex items-center justify-between gap-3"><div><strong className="text-sm text-slate-800">项目范围</strong><p className="mt-1 text-xs leading-5 text-slate-500">已选择 {draft.projectIds.length} 个项目。勾选的项目才会接收 Git 推送通知，并可供群机器人分析。</p></div><button type="button" onClick={() => setProjectSelectorOpen(true)} className={actionClass}>选择项目</button></div></div></div>
      <div className="mt-5 flex gap-2"><button disabled={busy} className={`${primaryClass} flex-1`}>{busy ? <Loader2 size={15} className="animate-spin" /> : <CheckCircle2 size={15} />}{editing ? "保存通道与项目" : "创建推送通道"}</button>{editing && <button type="button" onClick={resetEditor} className={actionClass}>取消</button>}</div><p className="mt-4 rounded-lg bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-500">测试会向真实钉钉群发送固定文本；Stream 机器人仅接收群内 @机器人 的文本，处理完成后使用钉钉 sessionWebhook 回到原群。</p></form></aside></div>{projectSelectorOpen && <ProjectSelectorDialog projects={projects} selectedIds={draft.projectIds} onChange={(projectIds) => setDraft((current) => ({ ...current, projectIds }))} onClose={() => setProjectSelectorOpen(false)} />}</section>;
}

function ProjectSelectorDialog({ projects, selectedIds, onChange, onClose }: { projects: CodeProject[]; selectedIds: number[]; onChange: (projectIds: number[]) => void; onClose: () => void }) {
  const [filter, setFilter] = useState("");
  const normalizedFilter = filter.trim().toLocaleLowerCase();
  const visibleProjects = projects.filter((project) => !normalizedFilter || `${project.display_name} ${project.name}`.toLocaleLowerCase().includes(normalizedFilter));
  const visibleIds = visibleProjects.map((project) => project.id);
  const selectedVisibleCount = visibleIds.filter((id) => selectedIds.includes(id)).length;
  const replaceVisibleSelection = (select: boolean) => onChange(select ? Array.from(new Set([...selectedIds, ...visibleIds])) : selectedIds.filter((id) => !visibleIds.includes(id)));
  const invertVisibleSelection = () => onChange(Array.from(new Set([...selectedIds.filter((id) => !visibleIds.includes(id)), ...visibleIds.filter((id) => !selectedIds.includes(id))])));
  const toggle = (projectId: number) => onChange(selectedIds.includes(projectId) ? selectedIds.filter((id) => id !== projectId) : [...selectedIds, projectId]);

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="presentation" onMouseDown={onClose}><section className="flex max-h-[82vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="push-project-selector-title" onMouseDown={(event) => event.stopPropagation()}><header className="flex items-start gap-3 border-b border-slate-100 px-5 py-4"><div className="min-w-0 flex-1"><h2 id="push-project-selector-title" className="text-base font-semibold text-slate-900">选择项目</h2><p className="mt-1 text-xs leading-5 text-slate-500">选择后请点击页面右侧的“保存通道与项目”才会生效。</p></div><button type="button" onClick={onClose} className="grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="关闭"><X size={17}/></button></header><div className="border-b border-slate-100 px-5 py-3"><label className="relative block"><Search size={16} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input autoFocus value={filter} onChange={(event) => setFilter(event.target.value)} className="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-50" placeholder="过滤项目名称或标识"/></label><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-slate-500">已选 {selectedIds.length} 个 · 当前列表 {selectedVisibleCount}/{visibleProjects.length} 个</span><div className="flex gap-2"><button type="button" onClick={() => replaceVisibleSelection(true)} disabled={!visibleProjects.length || selectedVisibleCount === visibleProjects.length} className={actionClass}>全选</button><button type="button" onClick={invertVisibleSelection} disabled={!visibleProjects.length} className={actionClass}>反选</button><button type="button" onClick={() => replaceVisibleSelection(false)} disabled={!selectedVisibleCount} className={actionClass}>取消全选</button></div></div></div><div className="min-h-0 flex-1 overflow-y-auto p-3">{visibleProjects.length === 0 ? <Empty text={projects.length ? "没有匹配的项目" : "暂无可选项目"} /> : <div className="space-y-1">{visibleProjects.map((project) => <label key={project.id} className="flex cursor-pointer items-center gap-3 rounded-lg px-3 py-2.5 hover:bg-slate-50"><input type="checkbox" checked={selectedIds.includes(project.id)} onChange={() => toggle(project.id)} className="h-4 w-4 accent-blue-600"/><span className="min-w-0"><span className="block truncate text-sm text-slate-800">{project.display_name}</span><span className="block truncate text-xs text-slate-400">{project.name}</span></span></label>)}</div>}</div><footer className="flex justify-end border-t border-slate-100 px-5 py-3"><button type="button" onClick={onClose} className={primaryClass}>完成选择</button></footer></section></div>;
}

function ChannelRow({ channel, busy, onEdit, onTest, onTestStream, onDelete }: { channel: PushChannel; busy: boolean; onEdit: (channel: PushChannel) => void; onTest: (channel: PushChannel) => void; onTestStream: (channel: PushChannel) => void; onDelete: (channel: PushChannel) => void }) {
  const streamReady = channel.stream_status === "connected" || channel.stream_status === "verified";
  const streamText = channel.stream_enabled ? streamReady ? "Stream 已连接" : `Stream ${channel.stream_status || "连接中"}` : "Stream 未启用";
  const lastCallback = channel.stream_last_callback_at ? `最近有效 @消息：${formatBeijingTime(channel.stream_last_callback_at)}` : "尚未收到有效 @消息回调";
  const lastFrame = channel.stream_last_frame_at ? `最后收到 Stream 帧：${formatBeijingTime(channel.stream_last_frame_at)}` : "暂未收到 Stream 帧";
  const reconnect = channel.stream_status === "reconnecting" && channel.stream_next_reconnect_at ? `第 ${channel.stream_reconnect_attempt || 1} 次重连将在 ${formatBeijingTime(channel.stream_next_reconnect_at)} 尝试` : null;
  return <div className="flex flex-wrap items-center gap-3 px-5 py-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-slate-800">{channel.name}</strong><Status success={channel.enabled} text={channel.enabled ? "通知已启用" : "通知已停用"} /><Status success={channel.stream_enabled && streamReady} text={streamText} /></div><p className="mt-1 text-xs text-slate-500">项目范围：{channel.project_names.length ? channel.project_names.join("、") : "未勾选"}</p><p className="mt-1 text-xs text-slate-400">{lastCallback} · {lastFrame}</p>{reconnect && <p className="mt-1 text-xs text-amber-700">{reconnect}</p>}<p className="mt-1 text-xs text-slate-400">Webhook token {channel.has_access_token ? "已保存" : "未保存"} · Stream Secret {channel.has_stream_client_secret ? "已保存" : "未保存"}{channel.stream_last_error_code ? ` · ${channel.stream_last_error_code}` : ""}</p></div><div className="flex flex-wrap items-center gap-2"><button disabled={busy || !channel.enabled} onClick={() => onTest(channel)} className={actionClass}><Send size={14} />Webhook 测试</button><button disabled={busy || !channel.has_stream_client_secret || !channel.stream_client_id || !channel.robot_code} onClick={() => onTestStream(channel)} className={actionClass}><Radio size={14} />Stream 测试</button><button disabled={busy} onClick={() => onEdit(channel)} className={actionClass}>编辑项目</button><button disabled={busy} onClick={() => onDelete(channel)} className={`${actionClass} text-red-600`}><Trash2 size={14} />删除</button></div></div>;
}
function formatBeijingTime(value: string) { return new Date(value).toLocaleString("zh-CN", { timeZone: "Asia/Shanghai", hour12: false }); }
function Panel({ title, detail, children }: { title: string; detail: string; children: ReactNode }) { return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-[15px] font-semibold">{title}</h2><p className="mt-1 text-xs text-slate-500">{detail}</p></div>{children}</section>; }
function Label({ text, children }: { text: string; children: ReactNode }) { return <label className="grid gap-1.5 text-xs font-medium text-slate-600"><span>{text}</span>{children}</label>; }
function Check({ text, checked, onChange }: { text: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-xs text-slate-700 hover:bg-slate-50"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />{text}</label>; }
function Status({ success, text }: { success: boolean; text: string }) { return <span className={`rounded-full px-2 py-0.5 text-[11px] ${success ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{text}</span>; }
function Empty({ text }: { text: string }) { return <p className="px-5 py-10 text-center text-sm text-slate-400">{text}</p>; }
function Loading() { return <div className="flex min-h-[300px] items-center justify-center text-sm text-slate-400"><RefreshCw size={17} className="mr-2 animate-spin" />正在加载推送模块…</div>; }
