"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CheckSquare, ExternalLink, Loader2, Plus, RefreshCw, Send, X } from "lucide-react";
import { getCodeProjects } from "@/lib/code-repository-api";
import type { CodeProject } from "@/lib/code-repository-types";
import { createProjectTask, listProjectTasks, syncGiteeTasks, type ProjectTask } from "@/lib/project-task-api";

export function TaskBoardPage() {
  const router = useRouter(); const [projects, setProjects] = useState<CodeProject[]>([]); const [tasks, setTasks] = useState<ProjectTask[]>([]); const [projectId, setProjectId] = useState<number | "all">("all"); const [loading, setLoading] = useState(true); const [syncing, setSyncing] = useState(false); const [error, setError] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [title, setTitle] = useState(""); const [description, setDescription] = useState("");
  const selectedProject = projects.find(x => x.id === projectId) ?? null;
  const visible = useMemo(() => projectId === "all" ? tasks : tasks.filter(x => x.project_id === projectId), [projectId, tasks]);
  const reload = async () => { setLoading(true); try { const [p, t] = await Promise.all([getCodeProjects(), listProjectTasks()]); setProjects(p); setTasks(t); } catch (e) { setError(e instanceof Error ? e.message : "无法加载任务。"); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, []);
  const openTask = (task: ProjectTask) => { const handoff = crypto.randomUUID(); const content = `请处理以下任务，并先结合当前项目代码评估实施方案。\n\n任务：${task.title}\n来源：${task.source === "gitee" ? "Gitee" : "AiAgent"}${task.status ? `\n状态：${task.status}` : ""}${task.assignee ? `\n负责人：${task.assignee}` : ""}${task.description ? `\n\n任务详情：\n${task.description}` : ""}${task.external_url ? `\n\n原始链接：${task.external_url}` : ""}`; sessionStorage.setItem("aiagent:pending-template-turn", JSON.stringify({ handoff_id: handoff, content, project_id: task.project_id })); router.push(`/chat?project=${task.project_id ?? ""}&template_handoff=${encodeURIComponent(handoff)}`); };
  const create = async () => { if (!title.trim()) return; try { const task = await createProjectTask({ project_id: selectedProject?.id, title, description }); setTasks(x => [task, ...x]); setTitle(""); setDescription(""); setCreating(false); } catch (e) { setError(e instanceof Error ? e.message : "创建任务失败。"); } };
  const sync = async () => { if (!selectedProject) { setError("请先选择一个项目后同步 Gitee 任务。"); return; } setSyncing(true); setError(null); try { await syncGiteeTasks(selectedProject.id); await reload(); } catch (e) { setError(e instanceof Error ? e.message : "同步失败。"); } finally { setSyncing(false); } };
  return <main className="min-h-screen bg-slate-50 px-4 py-6 lg:ml-[240px] lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.16em] text-blue-600">TASK WORKBENCH</p><h1 className="mt-1 text-2xl font-semibold text-slate-950">任务面板</h1><p className="mt-2 text-sm text-slate-500">在项目维度整理本地任务与 Gitee Issue；点击任务即可带着完整上下文进入对应项目的新会话。</p></div><div className="flex gap-2"><button onClick={sync} disabled={syncing} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 hover:bg-slate-100 disabled:opacity-60"><RefreshCw size={16} className={syncing ? "animate-spin" : ""}/>{syncing ? "同步中" : "同步 Gitee"}</button><button onClick={() => setCreating(true)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-3 text-sm font-medium text-white hover:bg-blue-700"><Plus size={16}/>新建任务</button></div></div>
  <div className="mt-6 flex flex-wrap gap-2">{[{ id: "all" as const, name: "全部项目" }, ...projects.map(x => ({ id: x.id, name: x.display_name }))].map(p => <button key={p.id} onClick={() => setProjectId(p.id)} className={`rounded-full px-3 py-1.5 text-sm ${projectId === p.id ? "bg-slate-900 text-white" : "border border-slate-200 bg-white text-slate-600 hover:bg-slate-100"}`}>{p.name}</button>)}</div>
  {error && <div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  {loading ? <div className="flex h-64 items-center justify-center text-slate-400"><Loader2 className="animate-spin"/> </div> : <section className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(task => <article key={task.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:border-blue-300 hover:shadow"><div className="flex items-start gap-3"><span className={`mt-0.5 grid h-8 w-8 place-items-center rounded-lg ${task.source === "gitee" ? "bg-orange-50 text-orange-600" : "bg-blue-50 text-blue-600"}`}><CheckSquare size={17}/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[11px] text-slate-500">{task.source === "gitee" ? "Gitee" : "本地"}</span><span className="text-[11px] text-slate-400">{task.project_name ?? "未归属项目"}</span></div><h2 className="mt-2 line-clamp-2 font-semibold text-slate-900">{task.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-5 text-slate-500">{task.description || "未提供任务说明"}</p><div className="mt-4 flex items-center justify-between gap-2"><span className="text-xs text-slate-400">{task.status || "open"}{task.assignee ? ` · ${task.assignee}` : ""}</span><div className="flex gap-1">{task.external_url && <a href={task.external_url} target="_blank" rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="打开 Gitee"><ExternalLink size={15}/></a>}<button onClick={() => openTask(task)} disabled={!task.project_id} title={task.project_id ? "在项目会话中处理" : "任务尚未关联项目"} className="inline-flex h-8 items-center gap-1 rounded-lg bg-blue-600 px-2.5 text-xs font-medium text-white hover:bg-blue-700 disabled:bg-slate-200"><Send size={13}/>处理</button></div></div></div></div></article>)}{visible.length === 0 && <div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center text-sm text-slate-400">暂无任务。选择项目后可同步 Gitee Issue，或创建一个本地任务。</div>}</section>}
  {creating && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><h2 className="font-semibold text-slate-900">新建任务</h2><p className="mt-1 text-xs text-slate-500">任务将创建在当前项目范围内。</p></div><button onClick={() => setCreating(false)} className="text-slate-400 hover:text-slate-700"><X/></button></div><label className="mt-5 block text-sm text-slate-700">项目<select value={selectedProject?.id ?? ""} onChange={e => setProjectId(Number(e.target.value))} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 px-3"><option value="">请选择项目</option>{projects.map(x => <option key={x.id} value={x.id}>{x.display_name}</option>)}</select></label><label className="mt-3 block text-sm text-slate-700">标题<input value={title} onChange={e => setTitle(e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 px-3" autoFocus/></label><label className="mt-3 block text-sm text-slate-700">说明<textarea value={description} onChange={e => setDescription(e.target.value)} className="mt-1.5 min-h-28 w-full rounded-lg border border-slate-200 p-3"/></label><div className="mt-5 flex justify-end gap-2"><button onClick={() => setCreating(false)} className="h-9 rounded-lg px-3 text-sm text-slate-600 hover:bg-slate-100">取消</button><button onClick={create} disabled={!selectedProject || !title.trim()} className="h-9 rounded-lg bg-blue-600 px-3 text-sm text-white disabled:bg-slate-200">创建并保存</button></div></div></div>}</div></main>;
}
