import { architectureTypes, type Architecture } from "./chat-architecture";

const escape = (text: string) => text.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);

/** SVG must come from the application's controlled renderer, never model HTML. */
export function architectureHtml(graph: Architecture, svg: string, dark: boolean): string {
  const groups = [...new Set(graph.nodes.map((node) => node.group || "未分组"))];
  const nodes = graph.nodes.map((node) => `<details><summary>${escape(node.label)}<small>${escape(node.group)}</small></summary><p>${escape(node.description || "暂无说明")}</p><p class="source">来源（模型标注）：${escape(node.source || "未提供")}</p></details>`).join("");
  const names = new Map(graph.nodes.map((node) => [node.id, node.label]));
  const edges = graph.edges.map((edge, index) => `<li><span>${String(index + 1).padStart(2, "0")}</span><strong>${escape(names.get(edge.from)!)} → ${escape(names.get(edge.to)!)}</strong><p>${escape(edge.label || "有向关系")}</p></li>`).join("");
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${escape(graph.title)}</title><style>
*{box-sizing:border-box}body{margin:0;padding:32px;background:${dark ? "#080f1c" : "#edf3f4"};color:${dark ? "#e2e8f0" : "#183344"};font:14px/1.65 system-ui,sans-serif}main{max-width:1600px;margin:auto;border:1px solid #67a7b780;border-radius:22px;overflow:hidden;background:${dark ? "#0b1220" : "#fff"};box-shadow:0 24px 64px #19384812}header{padding:28px 32px;border-bottom:1px solid #67a7b730}h1{margin:8px 0;font-size:clamp(20px,3vw,30px);font-weight:550;overflow-wrap:anywhere}.eyebrow{color:#0891b2;font-size:11px;letter-spacing:2px}header p,footer{font-size:12px;opacity:.7}.canvas{overflow:auto;background:${dark ? "#0b1220" : "#f6fbfc"}}svg{display:block;width:100%;height:auto;margin:0!important;max-width:none}#actual{margin:18px 8px 18px 32px;accent-color:#0891b2}#actual:checked~.canvas svg{width:auto}.legend{padding:14px 32px;border-block:1px solid #67a7b730;display:flex;flex-wrap:wrap;gap:16px;font-size:12px}.legend span:before{content:'◇';color:#0891b2;margin-right:6px}.reference{padding:24px 32px}h2{font-size:16px;margin:0 0 16px}details{border-top:1px solid #67a7b730;padding:12px 0}summary{cursor:pointer;font-weight:600;overflow-wrap:anywhere}summary small{font-weight:400;opacity:.65;margin-left:12px}p{white-space:pre-wrap;overflow-wrap:anywhere}.source{font-size:12px;opacity:.65}ol{list-style:none;padding:0;columns:2;column-gap:32px}li{break-inside:avoid;padding:12px 0;border-top:1px solid #67a7b730;overflow-wrap:anywhere}li span{color:#0891b2;margin-right:12px;font-size:11px}li p{margin:4px 0 0 28px;font-size:12px;opacity:.75}footer{padding:20px 32px;border-top:1px solid #67a7b730}@media(max-width:640px){body{padding:12px}header,.reference{padding:20px}ol{columns:1}}@media print{body{padding:0}main{box-shadow:none}#actual,label[for=actual]{display:none}#actual:checked~.canvas svg{width:100%}details p{display:block}}
</style></head><body><main><header><div class="eyebrow">${architectureTypes[graph.diagramType ?? "architecture"]} / ${graph.nodes.length} 个节点 · ${graph.edges.length} 条关系</div><h1>${escape(graph.title)}</h1><p>系统视图 · 图形与说明</p></header><input id="actual" type="checkbox"><label for="actual">原始尺寸阅读（可滚动）</label><div class="canvas">${svg}</div><div class="legend">图例 ${groups.map((group) => `<span>${escape(group)}</span>`).join("")}</div><section class="reference"><h2>节点说明与来源</h2>${nodes}</section><section class="reference"><h2>关系明细</h2><ol>${edges}</ol></section><footer>图形快照 · 来源为模型标注。交互探索请返回 AiAgent 会话。</footer></main></body></html>`;
}
