"use client";

import { useEffect, useState } from "react";
import { Braces, FileCode2, Folder, FolderOpen, Loader2, Search, X } from "lucide-react";
import { getCodeFile, getCodeRepositories, getCodeTree, grepCodeRepository, type CodeFile, type CodeGrepResult, type CodeTree } from "@/lib/code-repository-api";
import type { CodeRepository } from "@/lib/code-repository-types";

type Tab = "files" | "search" | "overview" | "index";
type OpenFile = CodeFile & { key: string };

export function CodeRepositoryCenter() {
  const [rows, setRows] = useState<CodeRepository[]>([]);
  const [selected, setSelected] = useState<CodeRepository | null>(null);
  useEffect(() => { void getCodeRepositories().then(setRows); }, []);
  if (selected) return <Detail repository={selected} onBack={() => setSelected(null)} />;
  return <main className="mx-auto max-w-6xl px-6 py-8"><div className="flex justify-between"><div><h1 className="text-3xl font-semibold">代码库</h1><p className="mt-2 text-sm text-zinc-500">实时读取、Live Grep 与按需代码理解。</p></div><button onClick={() => location.assign("/settings/code-repositories/manage")} className="rounded-md bg-blue-600 px-4 py-2 text-sm text-white">新建代码库</button></div><h2 className="mt-8 text-xs font-semibold text-zinc-600">搜索引擎</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><Card title="Live Grep" text="按问题实时读取相关源码，不要求建立索引。" state="就绪"/><Card title="项目概览" text="读取 README、清单和入口文件，避免遍历全部文件。" state="就绪"/><Card title="符号索引" text="可选缓存，用于大型仓库的快速定位。" state="可选"/><Card title="调用关系" text="按需收集引用与调用证据。" state="预留"/></div><h2 className="mt-8 text-xs font-semibold text-zinc-600">代码库 · {rows.length}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{rows.map(row => <button key={row.id} onClick={() => setSelected(row)} className="rounded-lg border p-4 text-left hover:border-blue-300"><div className="flex items-center gap-2 font-semibold"><Braces size={16}/>{row.display_name}</div><div className="mt-2 truncate text-xs text-zinc-500">{row.root_path}</div><div className="mt-2 text-xs text-emerald-700">{row.languages.join(" / ") || "未识别技术栈"}</div></button>)}</div></main>;
}

function Detail({ repository, onBack }: { repository: CodeRepository; onBack: () => void }) { const [tab,setTab]=useState<Tab>("files"); return <main className="flex min-h-screen flex-col"><header className="border-b px-6 py-5"><button onClick={onBack} className="text-xs text-zinc-500">← 代码库</button><h1 className="mt-3 text-xl font-semibold">{repository.display_name}</h1><p className="mt-1 text-xs text-zinc-500">{repository.languages.join(" / ")} · {repository.root_path}</p><nav className="mt-5 flex gap-5 text-sm">{(["files","search","overview","index"] as Tab[]).map(key=><button key={key} onClick={()=>setTab(key)} className={tab===key?"border-b-2 border-blue-600 pb-2":"pb-2 text-zinc-500"}>{({files:"文件",search:"实时搜索",overview:"概览",index:"索引缓存"})[key]}</button>)}</nav></header>{tab==="files"?<Files repository={repository}/>:tab==="search"?<LiveSearch repository={repository}/>:<div className="mx-auto max-w-3xl p-8 text-sm text-zinc-600">{tab==="overview"?"聊天会按需读取 README、构建清单和入口文件生成概览，不会遍历整个仓库。":"索引缓存用于提升符号与跨文件查询速度，不是实时理解代码库的前置条件。"}</div>}</main>; }

function Files({repository}:{repository:CodeRepository}) { const [trees,setTrees]=useState<Record<string,CodeTree>>({});const [open,setOpen]=useState<string[]>([""]);const [tabs,setTabs]=useState<OpenFile[]>([]);const [active,setActive]=useState<string>();useEffect(()=>{void load("");},[repository.name]);async function load(path:string){if(trees[path])return;setTrees(x=>({...x,[path]:{path,directories:[],files:[]}}));const tree=await getCodeTree(repository.name,path);setTrees(x=>({...x,[path]:tree}));}async function file(path:string){const found=tabs.find(x=>x.key===path);if(found){setActive(path);return;}const value=await getCodeFile(repository.name,path);setTabs(x=>[...x,{...value,key:path}]);setActive(path);}const current=tabs.find(x=>x.key===active);return <div className="grid flex-1 grid-cols-[280px_minmax(0,1fr)]"><aside className="border-r p-3"><b className="text-sm">文件</b><Tree tree={trees[""]} depth={0} open={open} trees={trees} toggle={async p=>{const expanded=open.includes(p);setOpen(x=>expanded?x.filter(v=>v!==p):[...x,p]);if(!expanded)await load(p);}} file={file}/></aside><section className="min-w-0 bg-zinc-50"><div className="flex min-h-10 border-b bg-white">{tabs.map(x=><button key={x.key} onClick={()=>setActive(x.key)} className="flex items-center gap-2 border-r px-3 text-xs"><FileCode2 size={13}/>{x.path.split(/[\\/]/).pop()}<X size={12} onClick={e=>{e.stopPropagation();setTabs(v=>v.filter(t=>t.key!==x.key));}}/></button>)}</div>{current?<pre className="h-[calc(100vh-160px)] overflow-auto p-4 text-xs leading-5">{current.content}</pre>:<div className="flex h-[calc(100vh-160px)] items-center justify-center text-sm text-zinc-500">选择左侧文件以预览</div>}</section></div>; }

function Tree({tree,depth,open,trees,toggle,file}:{tree?:CodeTree;depth:number;open:string[];trees:Record<string,CodeTree>;toggle:(p:string)=>void;file:(p:string)=>void}){if(!tree)return <Loader2 size={14} className="mt-3 animate-spin"/>;return <div className="mt-2">{tree.directories.map(d=><div key={d.path}><button onClick={()=>void toggle(d.path)} style={{paddingLeft:depth*14}} className="flex w-full items-center gap-1 rounded px-1 py-1 text-left text-sm hover:bg-zinc-100">{open.includes(d.path)?<FolderOpen size={14}/>:<Folder size={14}/>}<span className="truncate">{d.name}</span></button>{open.includes(d.path)&&<Tree tree={trees[d.path]} depth={depth+1} open={open} trees={trees} toggle={toggle} file={file}/>}</div>)}{tree.files.map(f=><button key={f.path} onClick={()=>void file(f.path)} style={{paddingLeft:depth*14+4}} className="flex w-full items-center gap-1 rounded px-1 py-1 text-left text-sm hover:bg-blue-50"><FileCode2 size={13}/><span className="truncate">{f.name}</span></button>)}</div>;}

function LiveSearch({repository}:{repository:CodeRepository}){const [query,setQuery]=useState("");const [results,setResults]=useState<CodeGrepResult[]>([]);const [loading,setLoading]=useState(false);async function run(){if(query.trim().length<2)return;setLoading(true);try{setResults((await grepCodeRepository(repository.name,query)).matches);}finally{setLoading(false);}}return <section className="mx-auto w-full max-w-4xl p-6"><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void run()} placeholder="搜索错误信息、类名、方法名或文本" className="h-10 flex-1 rounded-md border px-3 text-sm"/><button onClick={()=>void run()} className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 text-sm text-white"><Search size={15}/>{loading?"搜索中":"搜索"}</button></div><div className="mt-5 space-y-3">{results.map((r,i)=><article key={`${r.path}-${r.line}-${i}`} className="rounded-md border bg-white p-3"><div className="text-xs font-medium text-blue-700">{r.path}:{r.line}</div><pre className="mt-2 overflow-auto whitespace-pre-wrap text-xs leading-5 text-zinc-700">{r.preview}</pre></article>)}</div></section>}
function Card({title,text,state}:{title:string;text:string;state:string}){return <div className="rounded-lg border p-4"><div className="flex justify-between font-semibold"><span>{title}</span><span className="text-xs text-emerald-700">{state}</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">{text}</p></div>}
