import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import * as echarts from "echarts";
import "./styles.css";

const dataset = { id: "production-summary", updatedAt: new Date().toISOString(), rows: [{ hour: "08:00", output: 118, target: 120 }, { hour: "10:00", output: 236, target: 240 }, { hour: "12:00", output: 356, target: 360 }, { hour: "14:00", output: 492, target: 480 }, { hour: "16:00", output: 618, target: 600 }] };
const metrics = [{ label: "当日计划", value: "1,280", tone: "blue" }, { label: "完成数量", value: "918", tone: "green" }, { label: "设备稼动率", value: "86.4%", tone: "cyan" }, { label: "异常工单", value: "12", tone: "orange" }];

function EChart({ option }) { const ref = useRef(null); useEffect(() => { const chart = echarts.init(ref.current); chart.setOption(option); const resize = () => chart.resize(); window.addEventListener("resize", resize); return () => { window.removeEventListener("resize", resize); chart.dispose(); }; }, [option]); return <div ref={ref} className="chart" />; }
function App() { const [data, setData] = useState(dataset); const option = useMemo(() => ({ backgroundColor: "transparent", tooltip: { trigger: "axis" }, grid: { left: 38, right: 20, top: 20, bottom: 28 }, xAxis: { type: "category", data: data.rows.map(row => row.hour), axisLine: { lineStyle: { color: "#47637f" } } }, yAxis: { type: "value", splitLine: { lineStyle: { color: "#1d3957" } } }, series: [{ type: "line", smooth: true, data: data.rows.map(row => row.output), areaStyle: { color: "#1677ff33" }, lineStyle: { color: "#48a7ff", width: 3 }, symbol: "none" }, { type: "line", smooth: true, data: data.rows.map(row => row.target), lineStyle: { color: "#ffc53d", type: "dashed" }, symbol: "none" }] }), [data]); return <main className="screen"><header><div><small>AIAGENT · DATASET-CENTRIC OPERATIONS</small><h1>生产运营实时看板</h1></div><button onClick={() => setData({ ...data, updatedAt: new Date().toISOString() })}>刷新数据</button></header><section className="metrics">{metrics.map(metric => <article key={metric.label} className={`metric ${metric.tone}`}><span>{metric.label}</span><strong>{metric.value}</strong><em>来自指标语义层</em></article>)}</section><section className="panels"><article className="panel wide"><h2>产线完成趋势</h2><EChart option={option} /></article><article className="panel"><h2>数据集状态</h2><p>数据集：{data.id}</p><p>字段：hour / output / target</p><p>更新：{new Date(data.updatedAt).toLocaleTimeString()}</p><p className="hint">图表只消费配置化数据集，便于后续接入 API、缓存与权限层。</p></article></section></main>; }
createRoot(document.getElementById("root")).render(<App />);
